#!/usr/bin/env sh

# This script is used to run the CLI tool when using the docker-compose setup.
# The web container in docker-compose.yml is named "webhost".
CONTAINER_NAME=webhost

# Optional entrypoint command
COMMAND=$2
if [ -z "$COMMAND" ]; then
    COMMAND=bash
fi

docker exec -it $CONTAINER_NAME $COMMAND $3 $4 $5 $6 $7 $8 $9
